name: OpenWrt

on:
  push:
    branches: 
      - openwrt

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python python3 python-pip python3-pip python-ply python3-ply haveged lrzsz device-tree-compiler scons
    - name: Clone source
      run: |
        cd /home/runner
        git clone https://github.com/openwrt/openwrt.git
        sudo chmod -R 777 openwrt
        sudo chown -R runner:runner openwrt
        cd /home/runner/openwrt
        ./scripts/feeds update -a 
        ./scripts/feeds install -a
    - name: Clone config
      run: |
        cd /home/runner/openwrt
        #wget https://raw.githubusercontent.com/c2726139513/auto_build/openwrt/tp_wr741v5nd-3.config -O .config
        cp /home/runner/work/auto_build/auto_build/tp_wr741v5nd-3.config .config
        cd /home/runner/openwrt/target/linux/ar71xx/image
        #wget https://raw.githubusercontent.com/c2726139513/auto_build/openwrt/tiny-tp-link.mk -O tiny-tp-link.mk
        cp /home/runner/work/auto_build/auto_build/tiny-tp-link.mk ./
    - name: Build
      run: | 
        cd /home/runner/openwrt
        make -j1 V=s
    - name: Upload_bin
      run: |
        /home/runner/work/auto_build/auto_build/upload openwrt /home/runner/openwrt/bin wr741v5nd
    - name: Upload_dl
      run: |
        /home/runner/work/auto_build/auto_build/upload dl /home/runner/openwrt/dl
    - name: Package_bin
      uses: actions/upload-artifact@master
      with:
        name: openwrt_wr741v5nd
        path: /home/runner/openwrt/bin
    - name: Package_dl
      uses: actions/upload-artifact@master
      with:
        name: dl
        path: /home/runner/openwrt/dl
